name: Weekly Sync from Upstream

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点 UTC 执行
  workflow_dispatch:     # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/github/gitignore.git
          git fetch upstream

      - name: Merge upstream/main into local main
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "Already up to date"

      - name: Push merged changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
